version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: marketplace_mysql
    environment:
      MYSQL_DATABASE: marketplace_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: marketplace_user
      MYSQL_PASSWORD: marketplace_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: marketplace_mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://mysql:3306/marketplace_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      DB_USERNAME: marketplace_user
      DB_PASSWORD: marketplace_pass
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    ports:
      - "8081:8081"
    restart: on-failure

volumes:
  mysql_data:
