services:
  - type: web
    name: smart-service-marketplace
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8081
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_HOST
        value: localhost
      - key: MAIL_PORT
        value: 1025
      - key: RAZORPAY_KEY_ID
        value: rzp_test_placeholder
      - key: RAZORPAY_KEY_SECRET
        value: placeholder_secret
