spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

logging:
  level:
    com.example.marketplace: WARN
    org.springframework: ERROR
